[[PSQueries]]
json = {query_name = "BU_PARM_0216_QRY"}

[[PSQueries]]
json = {query_name = "BU_PARM_ENRL_DORM_QRY"}


[[SAPQueries]]
params = {BAPIName = "Z_HR_EMPLOYEE_OBJ_LIST", account = "HR"}


[[VDSQueries]]
json = {params = "filter=(%26(AffiliateAssignmentEndDate=*)(%26(!(PersonPrimaryAffiliation=staff))(!(PersonPrimaryAffiliation=faculty))))&sizeLimit=25000"}
